=begin
#Messente API

#No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

OpenAPI spec version: 0.0.1
Contact: messente@messente.com
Generated by: https://openapi-generator.tech
OpenAPI Generator version: 4.0.0-beta2

=end

require 'spec_helper'
require 'json'

# Unit tests for MessenteApi::DeliveryReportApi
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe 'DeliveryReportApi' do
  before do
    # run before each test
    @instance = MessenteApi::DeliveryReportApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of DeliveryReportApi' do
    it 'should create an instance of DeliveryReportApi' do
      expect(@instance).to be_instance_of(MessenteApi::DeliveryReportApi)
    end
  end

  # unit tests for retrieve_delivery_report
  # Retrieves the delivery report for the Omnimessage
  # @param omnimessage_id UUID of the Omnimessage to for which the delivery report is to be retrieved
  # @param [Hash] opts the optional parameters
  # @return [DeliveryReportResponse]
  describe 'retrieve_delivery_report test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

end
