=begin
#Messente API

#No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

OpenAPI spec version: 0.0.1
Contact: messente@messente.com
Generated by: https://openapi-generator.tech
OpenAPI Generator version: 4.0.0-beta2

=end

require 'spec_helper'
require 'json'
require 'date'

# Unit tests for MessenteApi::ErrorPhonebook
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe 'ErrorPhonebook' do
  before do
    # run before each test
    @instance = MessenteApi::ErrorPhonebook.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of ErrorPhonebook' do
    it 'should create an instance of ErrorPhonebook' do
      expect(@instance).to be_instance_of(MessenteApi::ErrorPhonebook)
    end
  end
  describe 'test attribute "errors"' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

end
