=begin
#Messente API

#No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

OpenAPI spec version: 0.0.1
Contact: messente@messente.com
Generated by: https://openapi-generator.tech
OpenAPI Generator version: 4.0.0-beta2

=end

require 'spec_helper'
require 'json'
require 'date'

# Unit tests for MessenteApi::ErrorCodePhonebook
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe 'ErrorCodePhonebook' do
  before do
    # run before each test
    @instance = MessenteApi::ErrorCodePhonebook.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of ErrorCodePhonebook' do
    it 'should create an instance of ErrorCodePhonebook' do
      expect(@instance).to be_instance_of(MessenteApi::ErrorCodePhonebook)
    end
  end
end
