=begin
#Messente API

#No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

OpenAPI spec version: 0.0.1
Contact: messente@messente.com
Generated by: https://openapi-generator.tech
OpenAPI Generator version: 4.0.0-beta2

=end

require 'date'

module MessenteApi
  class ErrorTitleOmnichannel
    
    NOT_FOUND = 'Not found'.freeze
    FORBIDDEN = 'Forbidden'.freeze
    UNAUTHORIZED = 'Unauthorized'.freeze
    INVALID_DATA = 'Invalid data'.freeze
    INTERNAL_SERVER_ERROR = 'Internal Server Error'.freeze
    MISSING_DATA = 'Missing data'.freeze
    METHOD_NOT_ALLOWED = 'Method not allowed'.freeze

    # Builds the enum from string
    # @param [String] The enum value in the form of the string
    # @return [String] The enum value
    def self.build_from_hash(value)
      new.build_from_hash(value)
    end

    # Builds the enum from string
    # @param [String] The enum value in the form of the string
    # @return [String] The enum value
    def build_from_hash(value)
      constantValues = ErrorTitleOmnichannel.constants.select { |c| ErrorTitleOmnichannel::const_get(c) == value }
      raise "Invalid ENUM value #{value} for class #ErrorTitleOmnichannel" if constantValues.empty?
      value
    end
  end

end
