=begin
#Messente API

#[Messente](https://messente.com) is a global provider of messaging and user verification services.  * Send and receive SMS, Viber and WhatsApp messages. * Manage contacts and groups. * Fetch detailed info about phone numbers. * Blacklist phone numbers to make sure you're not sending any unwanted messages.  Messente builds [tools](https://messente.com/documentation) to help organizations connect their services to people anywhere in the world.

The version of the OpenAPI document: 2.0.0
Contact: messente@messente.com
Generated by: https://openapi-generator.tech
Generator version: 7.11.0

=end

require 'date'
require 'time'

module MessenteApi
  class ErrorTitleOmnichannel
    NOT_FOUND = "Not found".freeze
    FORBIDDEN = "Forbidden".freeze
    UNAUTHORIZED = "Unauthorized".freeze
    INVALID_DATA = "Invalid data".freeze
    INTERNAL_SERVER_ERROR = "Internal Server Error".freeze
    MISSING_DATA = "Missing data".freeze
    METHOD_NOT_ALLOWED = "Method not allowed".freeze

    def self.all_vars
      @all_vars ||= [NOT_FOUND, FORBIDDEN, UNAUTHORIZED, INVALID_DATA, INTERNAL_SERVER_ERROR, MISSING_DATA, METHOD_NOT_ALLOWED].freeze
    end

    # Builds the enum from string
    # @param [String] The enum value in the form of the string
    # @return [String] The enum value
    def self.build_from_hash(value)
      new.build_from_hash(value)
    end

    # Builds the enum from string
    # @param [String] The enum value in the form of the string
    # @return [String] The enum value
    def build_from_hash(value)
      return value if ErrorTitleOmnichannel.all_vars.include?(value)
      raise "Invalid ENUM value #{value} for class #ErrorTitleOmnichannel"
    end
  end
end
