=begin
#Messente API

#No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

OpenAPI spec version: 0.0.1
Contact: messente@messente.com
Generated by: https://openapi-generator.tech
OpenAPI Generator version: 4.0.0-beta2

=end

require 'date'

module MessenteApi
  class ErrorCodePhonebook
    
    N201 = '201'.freeze
    N202 = '202'.freeze
    N203 = '203'.freeze
    N204 = '204'.freeze
    N244 = '244'.freeze
    N205 = '205'.freeze

    # Builds the enum from string
    # @param [String] The enum value in the form of the string
    # @return [String] The enum value
    def self.build_from_hash(value)
      new.build_from_hash(value)
    end

    # Builds the enum from string
    # @param [String] The enum value in the form of the string
    # @return [String] The enum value
    def build_from_hash(value)
      constantValues = ErrorCodePhonebook.constants.select { |c| ErrorCodePhonebook::const_get(c) == value }
      raise "Invalid ENUM value #{value} for class #ErrorCodePhonebook" if constantValues.empty?
      value
    end
  end

end
