=begin
#Messente API

#No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

OpenAPI spec version: 0.0.1
Contact: messente@messente.com
Generated by: https://openapi-generator.tech
OpenAPI Generator version: 4.0.0-beta2

=end

require 'date'

module MessenteApi
  class ErrorTitlePhonebook
    
    INVALID_DATA = 'Invalid data'.freeze
    UNAUTHORIZED = 'Unauthorized'.freeze
    MISSING_RESOURCE = 'Missing resource'.freeze
    CONFLICT = 'Conflict'.freeze
    CLIENT_ERROR = 'Client error'.freeze
    GENERAL_ERROR = 'General error'.freeze

    # Builds the enum from string
    # @param [String] The enum value in the form of the string
    # @return [String] The enum value
    def self.build_from_hash(value)
      new.build_from_hash(value)
    end

    # Builds the enum from string
    # @param [String] The enum value in the form of the string
    # @return [String] The enum value
    def build_from_hash(value)
      constantValues = ErrorTitlePhonebook.constants.select { |c| ErrorTitlePhonebook::const_get(c) == value }
      raise "Invalid ENUM value #{value} for class #ErrorTitlePhonebook" if constantValues.empty?
      value
    end
  end

end
