=begin
#Messente API

#[Messente](https://messente.com) is a global provider of messaging and user verification services.  * Send and receive SMS, Viber, WhatsApp and Telegram messages. * Manage contacts and groups. * Fetch detailed info about phone numbers. * Blacklist phone numbers to make sure you're not sending any unwanted messages.  Messente builds [tools](https://messente.com/documentation) to help organizations connect their services to people anywhere in the world.

The version of the OpenAPI document: 2.0.0
Contact: messente@messente.com
Generated by: https://openapi-generator.tech
Generator version: 7.6.0

=end

require 'date'
require 'time'

module MessenteApi
  class ErrorCodeOmnichannelMachine
    N0 = 0.freeze
    N1 = 1.freeze
    N2 = 2.freeze
    N3 = 3.freeze
    N4 = 4.freeze
    N5 = 5.freeze
    N6 = 6.freeze
    N7 = 7.freeze
    N8 = 8.freeze
    N9 = 9.freeze
    N10 = 10.freeze
    N999 = 999.freeze

    def self.all_vars
      @all_vars ||= [N0, N1, N2, N3, N4, N5, N6, N7, N8, N9, N10, N999].freeze
    end

    # Builds the enum from string
    # @param [String] The enum value in the form of the string
    # @return [String] The enum value
    def self.build_from_hash(value)
      new.build_from_hash(value)
    end

    # Builds the enum from string
    # @param [String] The enum value in the form of the string
    # @return [String] The enum value
    def build_from_hash(value)
      return value if ErrorCodeOmnichannelMachine.all_vars.include?(value)
      raise "Invalid ENUM value #{value} for class #ErrorCodeOmnichannelMachine"
    end
  end
end
