=begin
#Messente API

#No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

OpenAPI spec version: 0.0.1
Contact: messente@messente.com
Generated by: https://openapi-generator.tech
OpenAPI Generator version: 4.0.0-beta2

=end

require 'date'

module MessenteApi
  class ErrorCodeOmnichannel
    
    N101 = '101'.freeze
    N102 = '102'.freeze
    N103 = '103'.freeze
    N104 = '104'.freeze
    N105 = '105'.freeze
    N106 = '106'.freeze
    N107 = '107'.freeze

    # Builds the enum from string
    # @param [String] The enum value in the form of the string
    # @return [String] The enum value
    def self.build_from_hash(value)
      new.build_from_hash(value)
    end

    # Builds the enum from string
    # @param [String] The enum value in the form of the string
    # @return [String] The enum value
    def build_from_hash(value)
      constantValues = ErrorCodeOmnichannel.constants.select { |c| ErrorCodeOmnichannel::const_get(c) == value }
      raise "Invalid ENUM value #{value} for class #ErrorCodeOmnichannel" if constantValues.empty?
      value
    end
  end

end
