=begin
#Messente API

#[Messente](https://messente.com) is a global provider of messaging and user verification services.  * Send and receive SMS, Viber and WhatsApp messages. * Manage contacts and groups. * Fetch detailed info about phone numbers. * Blacklist phone numbers to make sure you're not sending any unwanted messages.  Messente builds [tools](https://messente.com/documentation) to help organizations connect their services to people anywhere in the world.

The version of the OpenAPI document: 2.1.0
Contact: messente@messente.com
Generated by: https://openapi-generator.tech
Generator version: 7.11.0

=end

require 'date'
require 'time'

module MessenteApi
  # RCS suggested action.
  class RcsSuggestedAction
    # The text of the suggested action. Exactly one of the action fields (types) must be provided.
    attr_accessor :text

    # The postback data associated with the suggested action. This is sent back to the sender when the user selects the suggested action.
    attr_accessor :postback_data

    # The fallback URL to open if the suggested action is not supported.
    attr_accessor :fallback_url

    attr_accessor :dial_action

    attr_accessor :view_location_action

    attr_accessor :create_calendar_event_action

    attr_accessor :open_url_action

    # This action does not have any properties. It simply triggers the share location action.
    attr_accessor :share_location_action

    # Attribute mapping from ruby-style variable name to JSON key.
    def self.attribute_map
      {
        :'text' => :'text',
        :'postback_data' => :'postback_data',
        :'fallback_url' => :'fallback_url',
        :'dial_action' => :'dial_action',
        :'view_location_action' => :'view_location_action',
        :'create_calendar_event_action' => :'create_calendar_event_action',
        :'open_url_action' => :'open_url_action',
        :'share_location_action' => :'share_location_action'
      }
    end

    # Returns all the JSON keys this model knows about
    def self.acceptable_attributes
      attribute_map.values
    end

    # Attribute type mapping.
    def self.openapi_types
      {
        :'text' => :'String',
        :'postback_data' => :'String',
        :'fallback_url' => :'String',
        :'dial_action' => :'RcsDialAction',
        :'view_location_action' => :'RcsViewLocationAction',
        :'create_calendar_event_action' => :'RcsCreateCalendarEventAction',
        :'open_url_action' => :'RcsOpenUrlAction',
        :'share_location_action' => :'Object'
      }
    end

    # List of attributes with nullable: true
    def self.openapi_nullable
      Set.new([
        :'fallback_url',
      ])
    end

    # Initializes the object
    # @param [Hash] attributes Model attributes in the form of hash
    def initialize(attributes = {})
      if (!attributes.is_a?(Hash))
        fail ArgumentError, "The input argument (attributes) must be a hash in `MessenteApi::RcsSuggestedAction` initialize method"
      end

      # check to see if the attribute exists and convert string to symbol for hash key
      attributes = attributes.each_with_object({}) { |(k, v), h|
        if (!self.class.attribute_map.key?(k.to_sym))
          fail ArgumentError, "`#{k}` is not a valid attribute in `MessenteApi::RcsSuggestedAction`. Please check the name to make sure it's valid. List of attributes: " + self.class.attribute_map.keys.inspect
        end
        h[k.to_sym] = v
      }

      if attributes.key?(:'text')
        self.text = attributes[:'text']
      else
        self.text = nil
      end

      if attributes.key?(:'postback_data')
        self.postback_data = attributes[:'postback_data']
      else
        self.postback_data = nil
      end

      if attributes.key?(:'fallback_url')
        self.fallback_url = attributes[:'fallback_url']
      end

      if attributes.key?(:'dial_action')
        self.dial_action = attributes[:'dial_action']
      end

      if attributes.key?(:'view_location_action')
        self.view_location_action = attributes[:'view_location_action']
      end

      if attributes.key?(:'create_calendar_event_action')
        self.create_calendar_event_action = attributes[:'create_calendar_event_action']
      end

      if attributes.key?(:'open_url_action')
        self.open_url_action = attributes[:'open_url_action']
      end

      if attributes.key?(:'share_location_action')
        self.share_location_action = attributes[:'share_location_action']
      end
    end

    # Show invalid properties with the reasons. Usually used together with valid?
    # @return Array for valid properties with the reasons
    def list_invalid_properties
      warn '[DEPRECATED] the `list_invalid_properties` method is obsolete'
      invalid_properties = Array.new
      if @text.nil?
        invalid_properties.push('invalid value for "text", text cannot be nil.')
      end

      if @text.to_s.length > 25
        invalid_properties.push('invalid value for "text", the character length must be smaller than or equal to 25.')
      end

      if @postback_data.nil?
        invalid_properties.push('invalid value for "postback_data", postback_data cannot be nil.')
      end

      if @postback_data.to_s.length > 2048
        invalid_properties.push('invalid value for "postback_data", the character length must be smaller than or equal to 2048.')
      end

      if !@fallback_url.nil? && @fallback_url.to_s.length > 2048
        invalid_properties.push('invalid value for "fallback_url", the character length must be smaller than or equal to 2048.')
      end

      invalid_properties
    end

    # Check to see if the all the properties in the model are valid
    # @return true if the model is valid
    def valid?
      warn '[DEPRECATED] the `valid?` method is obsolete'
      return false if @text.nil?
      return false if @text.to_s.length > 25
      return false if @postback_data.nil?
      return false if @postback_data.to_s.length > 2048
      return false if !@fallback_url.nil? && @fallback_url.to_s.length > 2048
      true
    end

    # Custom attribute writer method with validation
    # @param [Object] text Value to be assigned
    def text=(text)
      if text.nil?
        fail ArgumentError, 'text cannot be nil'
      end

      if text.to_s.length > 25
        fail ArgumentError, 'invalid value for "text", the character length must be smaller than or equal to 25.'
      end

      @text = text
    end

    # Custom attribute writer method with validation
    # @param [Object] postback_data Value to be assigned
    def postback_data=(postback_data)
      if postback_data.nil?
        fail ArgumentError, 'postback_data cannot be nil'
      end

      if postback_data.to_s.length > 2048
        fail ArgumentError, 'invalid value for "postback_data", the character length must be smaller than or equal to 2048.'
      end

      @postback_data = postback_data
    end

    # Custom attribute writer method with validation
    # @param [Object] fallback_url Value to be assigned
    def fallback_url=(fallback_url)
      if !fallback_url.nil? && fallback_url.to_s.length > 2048
        fail ArgumentError, 'invalid value for "fallback_url", the character length must be smaller than or equal to 2048.'
      end

      @fallback_url = fallback_url
    end

    # Checks equality by comparing each attribute.
    # @param [Object] Object to be compared
    def ==(o)
      return true if self.equal?(o)
      self.class == o.class &&
          text == o.text &&
          postback_data == o.postback_data &&
          fallback_url == o.fallback_url &&
          dial_action == o.dial_action &&
          view_location_action == o.view_location_action &&
          create_calendar_event_action == o.create_calendar_event_action &&
          open_url_action == o.open_url_action &&
          share_location_action == o.share_location_action
    end

    # @see the `==` method
    # @param [Object] Object to be compared
    def eql?(o)
      self == o
    end

    # Calculates hash code according to all attributes.
    # @return [Integer] Hash code
    def hash
      [text, postback_data, fallback_url, dial_action, view_location_action, create_calendar_event_action, open_url_action, share_location_action].hash
    end

    # Builds the object from hash
    # @param [Hash] attributes Model attributes in the form of hash
    # @return [Object] Returns the model itself
    def self.build_from_hash(attributes)
      return nil unless attributes.is_a?(Hash)
      attributes = attributes.transform_keys(&:to_sym)
      transformed_hash = {}
      openapi_types.each_pair do |key, type|
        if attributes.key?(attribute_map[key]) && attributes[attribute_map[key]].nil?
          transformed_hash["#{key}"] = nil
        elsif type =~ /\AArray<(.*)>/i
          # check to ensure the input is an array given that the attribute
          # is documented as an array but the input is not
          if attributes[attribute_map[key]].is_a?(Array)
            transformed_hash["#{key}"] = attributes[attribute_map[key]].map { |v| _deserialize($1, v) }
          end
        elsif !attributes[attribute_map[key]].nil?
          transformed_hash["#{key}"] = _deserialize(type, attributes[attribute_map[key]])
        end
      end
      new(transformed_hash)
    end

    # Deserializes the data based on type
    # @param string type Data type
    # @param string value Value to be deserialized
    # @return [Object] Deserialized data
    def self._deserialize(type, value)
      case type.to_sym
      when :Time
        Time.parse(value)
      when :Date
        Date.parse(value)
      when :String
        value.to_s
      when :Integer
        value.to_i
      when :Float
        value.to_f
      when :Boolean
        if value.to_s =~ /\A(true|t|yes|y|1)\z/i
          true
        else
          false
        end
      when :Object
        # generic object (usually a Hash), return directly
        value
      when /\AArray<(?<inner_type>.+)>\z/
        inner_type = Regexp.last_match[:inner_type]
        value.map { |v| _deserialize(inner_type, v) }
      when /\AHash<(?<k_type>.+?), (?<v_type>.+)>\z/
        k_type = Regexp.last_match[:k_type]
        v_type = Regexp.last_match[:v_type]
        {}.tap do |hash|
          value.each do |k, v|
            hash[_deserialize(k_type, k)] = _deserialize(v_type, v)
          end
        end
      else # model
        # models (e.g. Pet) or oneOf
        klass = MessenteApi.const_get(type)
        klass.respond_to?(:openapi_any_of) || klass.respond_to?(:openapi_one_of) ? klass.build(value) : klass.build_from_hash(value)
      end
    end

    # Returns the string representation of the object
    # @return [String] String presentation of the object
    def to_s
      to_hash.to_s
    end

    # to_body is an alias to to_hash (backward compatibility)
    # @return [Hash] Returns the object in the form of hash
    def to_body
      to_hash
    end

    # Returns the object in the form of hash
    # @return [Hash] Returns the object in the form of hash
    def to_hash
      hash = {}
      self.class.attribute_map.each_pair do |attr, param|
        value = self.send(attr)
        if value.nil?
          is_nullable = self.class.openapi_nullable.include?(attr)
          next if !is_nullable || (is_nullable && !instance_variable_defined?(:"@#{attr}"))
        end

        hash[param] = _to_hash(value)
      end
      hash
    end

    # Outputs non-array value in the form of hash
    # For object, use to_hash. Otherwise, just return the value
    # @param [Object] value Any valid value
    # @return [Hash] Returns the value in the form of hash
    def _to_hash(value)
      if value.is_a?(Array)
        value.compact.map { |v| _to_hash(v) }
      elsif value.is_a?(Hash)
        {}.tap do |hash|
          value.each { |k, v| hash[k] = _to_hash(v) }
        end
      elsif value.respond_to? :to_hash
        value.to_hash
      else
        value
      end
    end

  end

end
