=begin
#Messente API

#[Messente](https://messente.com) is a global provider of messaging and user verification services.  * Send and receive SMS, Viber, WhatsApp and Telegram messages. * Manage contacts and groups. * Fetch detailed info about phone numbers. * Blacklist phone numbers to make sure you're not sending any unwanted messages.  Messente builds [tools](https://messente.com/documentation) to help organizations connect their services to people anywhere in the world.

The version of the OpenAPI document: 2.0.0
Contact: messente@messente.com
Generated by: https://openapi-generator.tech
Generator version: 7.6.0

=end

require 'date'
require 'time'

module MessenteApi
  class Status
    ACK = "ACK".freeze
    DELIVRD = "DELIVRD".freeze
    UNDELIV = "UNDELIV".freeze
    FAILED = "FAILED".freeze
    UNKNOWN = "UNKNOWN".freeze
    ACCEPTD = "ACCEPTD".freeze
    REJECTD = "REJECTD".freeze
    DELETED = "DELETED".freeze
    EXPIRED = "EXPIRED".freeze
    NACK = "NACK".freeze
    SEEN = "SEEN".freeze

    def self.all_vars
      @all_vars ||= [ACK, DELIVRD, UNDELIV, FAILED, UNKNOWN, ACCEPTD, REJECTD, DELETED, EXPIRED, NACK, SEEN].freeze
    end

    # Builds the enum from string
    # @param [String] The enum value in the form of the string
    # @return [String] The enum value
    def self.build_from_hash(value)
      new.build_from_hash(value)
    end

    # Builds the enum from string
    # @param [String] The enum value in the form of the string
    # @return [String] The enum value
    def build_from_hash(value)
      return value if Status.all_vars.include?(value)
      raise "Invalid ENUM value #{value} for class #Status"
    end
  end
end
